name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: "test test action"
    steps:
      - uses: actions/checkout@v3
      - uses: black-sliver/test-action@main
      - uses: black-sliver/test-action@main
        with:
          strict: false
      - uses: black-sliver/test-action@main
        with:
          strict: true

